#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
ENV_FILE="${SPIRITUAL_WIZARD_STATE:-/tmp/spiritual-collective-cloudflare.env}"
PROJECT_DIR="${SPIRITUAL_COLLECTIVE_DIR:-/Users/andrew/projects/spiritual-collective}"
DOMAIN="spiritual-collective.com"
PRODUCTION_DOMAIN="www.${DOMAIN}"
BETA_DOMAIN="beta.${DOMAIN}"

banner "Spiritual Collective · Cloudflare Pages setup"

stage "Preflight: protect DNS and mail"
say "Nothing changes in this stage. We record the working state before touching hosting."
if [[ ! -d "$PROJECT_DIR/.git" ]]; then
  warn "repository not found at $PROJECT_DIR"
  say "Re-run with SPIRITUAL_COLLECTIVE_DIR=/absolute/path/to/the/repository"
  exit 1
fi
step "Make sure the deployment PR has been merged to main before creating the projects."
step "Compare Squarespace DNS with docs/runbooks/accountability-mailbox.md#as-provisioned."
if command -v dig >/dev/null 2>&1; then
  say "Current public mail records:"
  dig +short MX "$DOMAIN" || true
  dig +short TXT "$DOMAIN" || true
  dig +short CNAME "fm1._domainkey.${DOMAIN}" || true
  dig +short CNAME "fm2._domainkey.${DOMAIN}" || true
  dig +short CNAME "fm3._domainkey.${DOMAIN}" || true
  dig +short TXT "_dmarc.${DOMAIN}" || true
else
  warn "dig is unavailable; compare the records in Squarespace manually."
fi
open_url "https://account.squarespace.com/domains"
pause "Press Enter after every Fastmail record matches the runbook."
confirm "Have you confirmed the mailbox can currently send and receive?" || exit 1

stage "Create the production Pages project"
say "Production builds main with SITE_BUILD unset, so only approved records are offered."
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Create application → Pages → Import an existing Git repository."
step "Choose inarush0/spiritual-collective and set Production branch to main."
step "Set Build command to: npm run gates && npm run build"
step "Set Build output directory to: dist   and Root directory to: /"
step "Leave SITE_BUILD unset. Disable preview branch deployments and Web Analytics."
step "Keep automatic production deployments on; do not enable an Access policy."
step "After the first successful build, add www.spiritual-collective.com under Custom domains."
ask PRODUCTION_PAGES_HOST "Paste the generated production hostname (for example project.pages.dev):"
case "$PRODUCTION_PAGES_HOST" in
  *.pages.dev) ;;
  *) warn "expected a hostname ending in .pages.dev"; exit 1 ;;
esac
write_env PRODUCTION_PAGES_HOST "$PRODUCTION_PAGES_HOST"

stage "Create the beta Pages project"
say "Beta uses the same repo, branch, and settings; SITE_BUILD=beta is the only behavior change."
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Create a second Pages project from inarush0/spiritual-collective on main."
step "Use the same build command, output directory, root, and branch controls as production."
step "In the production environment variables, set SITE_BUILD to: beta"
step "Disable Web Analytics and do not enable an Access policy."
step "After the first successful build, add beta.spiritual-collective.com under Custom domains."
ask BETA_PAGES_HOST "Paste the generated beta hostname (for example project-beta.pages.dev):"
case "$BETA_PAGES_HOST" in
  *.pages.dev) ;;
  *) warn "expected a hostname ending in .pages.dev"; exit 1 ;;
esac
write_env BETA_PAGES_HOST "$BETA_PAGES_HOST"

stage "Connect Squarespace DNS and the apex redirect"
say "Add both CNAMEs before apex forwarding; Squarespace locks DNS editing while forwarding is active."
say "  www  CNAME  $PRODUCTION_PAGES_HOST"
say "  beta CNAME  $BETA_PAGES_HOST"
warn "A mistaken DNS edit can interrupt the accountability mailbox. Do not alter MX or TXT records."
confirm "Ready to add exactly these two CNAMEs and then the apex forwarding rule?" || exit 1
open_url "https://account.squarespace.com/domains"
step "Add CNAME www → $PRODUCTION_PAGES_HOST"
step "Add CNAME beta → $BETA_PAGES_HOST"
step "Confirm Pages shows both custom domains active with TLS."
step "Add a permanent (301) forwarding rule: @ → www.spiritual-collective.com"
step "Keep SSL on and choose Maintain paths. Add the forwarding rule last."
pause "Press Enter after both custom domains and the apex redirect are active."
if command -v dig >/dev/null 2>&1; then
  say "Observed web records:"
  dig +short CNAME "$PRODUCTION_DOMAIN" || true
  dig +short CNAME "$BETA_DOMAIN" || true
fi
if command -v curl >/dev/null 2>&1; then
  say "Observed apex response:"
  curl -sS -o /dev/null -D - "https://${DOMAIN}/" | sed -n '1,12p' || true
fi
confirm "Does the apex redirect to https://www.spiritual-collective.com/ and preserve paths?" || exit 1
confirm "After the DNS change, can the Fastmail mailbox still send and receive?" || exit 1

stage "Redirect the generated Pages hostnames"
say "The custom domains are canonical; the generated Pages hostnames should lead to them."
open_url "https://dash.cloudflare.com/?to=/:account/bulk-redirects"
step "Create a 301 redirect: https://$PRODUCTION_PAGES_HOST → https://$PRODUCTION_DOMAIN"
step "Create a 301 redirect: https://$BETA_PAGES_HOST → https://$BETA_DOMAIN"
step "For both, enable Preserve query string, Subpath matching, Preserve path suffix, and Include subdomains."
pause "Press Enter after both redirects are active."
if command -v curl >/dev/null 2>&1; then
  curl -sS -o /dev/null -D - "https://${PRODUCTION_PAGES_HOST}/about/" | sed -n '1,12p' || true
  curl -sS -o /dev/null -D - "https://${BETA_PAGES_HOST}/about/" | sed -n '1,12p' || true
fi
confirm "Do both generated hostnames redirect to the matching custom domain?" || exit 1

stage "Verify the live releases and record evidence"
say "This runs the repository's automated live assertion against the canonical domains."
(
  cd "$PROJECT_DIR"
  npm run verify:deployment -- "https://${PRODUCTION_DOMAIN}" "https://${BETA_DOMAIN}"
)
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Confirm both projects deploy automatically from main and preview branches are disabled."
step "Confirm Web Analytics, Logpush, Log Explorer, and optional request-log retention are disabled."
ask VERIFICATION_ROLE "Role recording this verification (normally editor):"
VERIFICATION_DATE=$(date +%F)
write_env VERIFICATION_ROLE "$VERIFICATION_ROLE"
write_env VERIFICATION_DATE "$VERIFICATION_DATE"
SKIPPED+=("Update docs/data-flow-audit.md in a follow-up PR: role=$VERIFICATION_ROLE, date=$VERIFICATION_DATE, production=$PRODUCTION_PAGES_HOST, beta=$BETA_PAGES_HOST")
SKIPPED+=("Complete sitting 2 in docs/runbooks/accountability-mailbox.md after the deployment PR is merged")

finish
